# Generated by Django 3.1.4 on 2021-01-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_userresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='questionnaire_questions',
            field=models.JSONField(default=1111),
            preserve_default=False,
        ),
    ]
