# Generated by Django 3.1.4 on 2021-01-07 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_authentication', '0002_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_clients',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'agents'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='speciality',
            field=models.CharField(choices=[('T', 'Term Insurance'), ('P', 'Permanent Insurance'), ('CI', 'Critical Illness Insurance'), ('LT', 'Long Term Care Insurance')], default='T', max_length=2),
        ),
    ]
