# Generated by Django 3.1.4 on 2021-01-07 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_authentication', '0003_auto_20210107_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='assigned_clients',
        ),
        migrations.AddField(
            model_name='customuser',
            name='assigned_clients',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'agents'}, related_name='_customuser_assigned_clients_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
